
import java.awt.FlowLayout;
import java.awt.PopupMenu;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.sql.*;
import java.util.logging.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author riani
 */
public class Movies extends javax.swing.JFrame {

    private PopupMenu openReportSelection;
    private PopupMenu closeButton;

    /**
     * Creates new form Movies
     */
    public Movies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDashboard = new javax.swing.JPanel();
        menuMoviesHead = new javax.swing.JLabel();
        menuDashboard = new javax.swing.JLabel();
        sidebarDashboard = new javax.swing.JLabel();
        panelMoviesHead = new javax.swing.JPanel();
        menuCategories = new javax.swing.JLabel();
        menuMovies = new javax.swing.JLabel();
        menuDashboard1 = new javax.swing.JLabel();
        sidebarMoviesHead = new javax.swing.JLabel();
        panelMovies = new javax.swing.JPanel();
        menuCategories1 = new javax.swing.JLabel();
        menuDashboard2 = new javax.swing.JLabel();
        sidebarMovies = new javax.swing.JLabel();
        panelCategories = new javax.swing.JPanel();
        menuMovies2 = new javax.swing.JLabel();
        menuDashboard3 = new javax.swing.JLabel();
        sidebarCategories = new javax.swing.JLabel();
        mainPageDashboard = new javax.swing.JPanel();
        countStaff = new javax.swing.JLabel();
        countCustomer = new javax.swing.JLabel();
        countMovies = new javax.swing.JLabel();
        pageDashboard = new javax.swing.JLabel();
        mainPageMovies = new javax.swing.JPanel();
        panelSortDef = new javax.swing.JPanel();
        sortRatingDef = new javax.swing.JLabel();
        sortYearDef = new javax.swing.JLabel();
        sortTitleDef = new javax.swing.JLabel();
        sortDef = new javax.swing.JLabel();
        panelSortRating = new javax.swing.JPanel();
        sortRatingRating = new javax.swing.JLabel();
        sortYearRating = new javax.swing.JLabel();
        sortTitleRating = new javax.swing.JLabel();
        sortRating = new javax.swing.JLabel();
        panelSortYear = new javax.swing.JPanel();
        sortRatingYear = new javax.swing.JLabel();
        sortYearYear = new javax.swing.JLabel();
        sortTitleYear = new javax.swing.JLabel();
        sortYear = new javax.swing.JLabel();
        panelSortTitle = new javax.swing.JPanel();
        sortRatingTitle = new javax.swing.JLabel();
        sortYearTitle = new javax.swing.JLabel();
        sortTitleTitle = new javax.swing.JLabel();
        sortTitle = new javax.swing.JLabel();
        sortingLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        addMovies = new javax.swing.JButton();
        pageMovies = new javax.swing.JLabel();
        mainPageCategories = new javax.swing.JPanel();
        pageCategories = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 230, 210));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuMoviesHead.setToolTipText("");
        menuMoviesHead.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuMoviesHead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMoviesHeadMouseClicked(evt);
            }
        });
        panelDashboard.add(menuMoviesHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 150, 18));

        menuDashboard.setToolTipText("");
        panelDashboard.add(menuDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 268, 150, 18));

        sidebarDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        sidebarDashboard.setText("S");
        panelDashboard.add(sidebarDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 650));

        getContentPane().add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 650));

        panelMoviesHead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuCategories.setToolTipText("");
        menuCategories.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCategoriesMouseClicked(evt);
            }
        });
        panelMoviesHead.add(menuCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 372, 120, 20));

        menuMovies.setToolTipText("");
        menuMovies.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuMovies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMoviesMouseClicked(evt);
            }
        });
        panelMoviesHead.add(menuMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 120, 20));

        menuDashboard1.setToolTipText("");
        menuDashboard1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuDashboard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDashboard1MouseClicked(evt);
            }
        });
        panelMoviesHead.add(menuDashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 268, 150, 18));

        sidebarMoviesHead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movieshead.png"))); // NOI18N
        sidebarMoviesHead.setText("S");
        panelMoviesHead.add(sidebarMoviesHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 650));

        getContentPane().add(panelMoviesHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 650));

        panelMovies.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuCategories1.setToolTipText("");
        menuCategories1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCategories1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCategories1MouseClicked(evt);
            }
        });
        panelMovies.add(menuCategories1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 372, 120, 20));

        menuDashboard2.setToolTipText("");
        menuDashboard2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuDashboard2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDashboard2MouseClicked(evt);
            }
        });
        panelMovies.add(menuDashboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 268, 150, 18));

        sidebarMovies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movies.png"))); // NOI18N
        sidebarMovies.setText("S");
        panelMovies.add(sidebarMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 650));

        getContentPane().add(panelMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 650));

        panelCategories.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuMovies2.setToolTipText("");
        menuMovies2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuMovies2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMovies2MouseClicked(evt);
            }
        });
        panelCategories.add(menuMovies2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 120, 20));

        menuDashboard3.setToolTipText("");
        menuDashboard3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuDashboard3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDashboard3MouseClicked(evt);
            }
        });
        panelCategories.add(menuDashboard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 268, 150, 18));

        sidebarCategories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/category.png"))); // NOI18N
        sidebarCategories.setText("S");
        panelCategories.add(sidebarCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 650));

        getContentPane().add(panelCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 650));

        mainPageDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        countStaff.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        countStaff.setForeground(new java.awt.Color(139, 138, 142));
        countStaff.setText("20");
        mainPageDashboard.add(countStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        countCustomer.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        countCustomer.setForeground(new java.awt.Color(139, 138, 142));
        countCustomer.setText("50");
        mainPageDashboard.add(countCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        countMovies.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        countMovies.setForeground(new java.awt.Color(255, 255, 255));
        countMovies.setText("1350");
        mainPageDashboard.add(countMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        pageDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardright.png"))); // NOI18N
        mainPageDashboard.add(pageDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 650));

        getContentPane().add(mainPageDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        mainPageMovies.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSortDef.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sortRatingDef.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortRatingDef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortRatingDefMouseClicked(evt);
            }
        });
        panelSortDef.add(sortRatingDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 0, 37, 18));

        sortYearDef.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortYearDef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortYearDefMouseClicked(evt);
            }
        });
        panelSortDef.add(sortYearDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, 37, 18));

        sortTitleDef.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortTitleDef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortTitleDefMouseClicked(evt);
            }
        });
        panelSortDef.add(sortTitleDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 37, 18));

        sortDef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sortingdesc.png"))); // NOI18N
        panelSortDef.add(sortDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 109, 18));

        mainPageMovies.add(panelSortDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 109, 18));

        panelSortRating.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sortRatingRating.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelSortRating.add(sortRatingRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 0, 37, 18));

        sortYearRating.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortYearRating.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortYearRatingMouseClicked(evt);
            }
        });
        panelSortRating.add(sortYearRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, 37, 18));

        sortTitleRating.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortTitleRating.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortTitleRatingMouseClicked(evt);
            }
        });
        panelSortRating.add(sortTitleRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 37, 18));

        sortRating.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sortrating.png"))); // NOI18N
        panelSortRating.add(sortRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 109, 18));

        mainPageMovies.add(panelSortRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 109, 18));

        panelSortYear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sortRatingYear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortRatingYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortRatingYearMouseClicked(evt);
            }
        });
        panelSortYear.add(sortRatingYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 0, 37, 18));
        panelSortYear.add(sortYearYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, 37, 18));

        sortTitleYear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortTitleYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortTitleYearMouseClicked(evt);
            }
        });
        panelSortYear.add(sortTitleYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 37, 18));

        sortYear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sortyear.png"))); // NOI18N
        panelSortYear.add(sortYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 109, 18));

        mainPageMovies.add(panelSortYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 109, 18));

        panelSortTitle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sortRatingTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortRatingTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortRatingTitleMouseClicked(evt);
            }
        });
        panelSortTitle.add(sortRatingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 0, 37, 18));

        sortYearTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortYearTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sortYearTitleMouseClicked(evt);
            }
        });
        panelSortTitle.add(sortYearTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, 37, 18));
        panelSortTitle.add(sortTitleTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 37, 18));

        sortTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorttitle.png"))); // NOI18N
        panelSortTitle.add(sortTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 109, 18));

        mainPageMovies.add(panelSortTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 109, 18));

        sortingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sorting.png"))); // NOI18N
        mainPageMovies.add(sortingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 56, 13));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Title", "Release Year", "Desc", "Rating", "Language"
            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        mainPageMovies.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 650, 390));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttondelete.png"))); // NOI18N
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusable(false);
        btnDelete.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        mainPageMovies.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 106, 27));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonupdate.png"))); // NOI18N
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setFocusable(false);
        btnUpdate.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mainPageMovies.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 106, 27));

        addMovies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonadd.png"))); // NOI18N
        addMovies.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMovies.setFocusable(false);
        addMovies.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mainPageMovies.add(addMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 106, 27));

        pageMovies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgmovies.png"))); // NOI18N
        mainPageMovies.add(pageMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 650));

        getContentPane().add(mainPageMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        mainPageCategories.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pageCategories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgcategories.png"))); // NOI18N
        mainPageCategories.add(pageCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 650));

        getContentPane().add(mainPageCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMoviesHeadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMoviesHeadMouseClicked
        // TODO add your handling code here:
        panelDashboard.setVisible(false);
        panelCategories.setVisible(false);
        panelMovies.setVisible(false);
        panelMoviesHead.setVisible(true);
    }//GEN-LAST:event_menuMoviesHeadMouseClicked

    private void menuMoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMoviesMouseClicked
        // TODO add your handling code here:
        panelDashboard.setVisible(false);
        panelMoviesHead.setVisible(false);
        panelCategories.setVisible(false);
        panelMovies.setVisible(true);
        mainPageDashboard.setVisible(false);
        mainPageMovies.setVisible(true);
        mainPageCategories.setVisible(false);
        panelSortDef.setVisible(true);
        panelSortTitle.setVisible(false);
        panelSortYear.setVisible(false);
        panelSortRating.setVisible(false);
    }//GEN-LAST:event_menuMoviesMouseClicked

    private void menuDashboard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboard1MouseClicked
        // TODO add your handling code here:
        panelDashboard.setVisible(true);
        panelMoviesHead.setVisible(false);
        panelMovies.setVisible(false);
        panelCategories.setVisible(false);
        mainPageMovies.setVisible(false);
        mainPageCategories.setVisible(false);
    }//GEN-LAST:event_menuDashboard1MouseClicked

    private void menuCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCategoriesMouseClicked
        // TODO add your handling code here:
        panelCategories.setVisible(true);
        panelDashboard.setVisible(false);
        panelMoviesHead.setVisible(false);
        panelMovies.setVisible(false);
        mainPageCategories.setVisible(true);
        mainPageMovies.setVisible(false);
        mainPageDashboard.setVisible(false);
    }//GEN-LAST:event_menuCategoriesMouseClicked

    private void menuCategories1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCategories1MouseClicked
        // TODO add your handling code here:
        panelCategories.setVisible(true);
        panelDashboard.setVisible(false);
        panelMoviesHead.setVisible(false);
        panelMovies.setVisible(false);
        mainPageCategories.setVisible(true);
        mainPageMovies.setVisible(false);
        mainPageDashboard.setVisible(false);
    }//GEN-LAST:event_menuCategories1MouseClicked

    private void menuDashboard2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboard2MouseClicked
        // TODO add your handling code here:
        panelDashboard.setVisible(true);
        mainPageDashboard.setVisible(true);
        panelMoviesHead.setVisible(false);
        mainPageMovies.setVisible(false);
        mainPageCategories.setVisible(false);
    }//GEN-LAST:event_menuDashboard2MouseClicked

    private void menuMovies2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMovies2MouseClicked
        // TODO add your handling code here:
        panelDashboard.setVisible(false);
        panelMoviesHead.setVisible(false);
        panelCategories.setVisible(false);
        panelMovies.setVisible(true);
        mainPageDashboard.setVisible(false);
        mainPageMovies.setVisible(true);
        mainPageCategories.setVisible(false);
        panelSortDef.setVisible(true);
        panelSortTitle.setVisible(false);
        panelSortYear.setVisible(false);
        panelSortRating.setVisible(false);
    }//GEN-LAST:event_menuMovies2MouseClicked

    private void menuDashboard3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboard3MouseClicked
        // TODO add your handling code here:
        panelDashboard.setVisible(true);
        mainPageDashboard.setVisible(true);
        panelMoviesHead.setVisible(false);
        panelMovies.setVisible(false);
        panelCategories.setVisible(false);
        mainPageMovies.setVisible(false);
        mainPageCategories.setVisible(false);
    }//GEN-LAST:event_menuDashboard3MouseClicked

    private void sortTitleDefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortTitleDefMouseClicked
        // TODO add your handling code here:
        panelSortDef.setVisible(false);
        panelSortTitle.setVisible(true);
        panelSortYear.setVisible(false);
        panelSortRating.setVisible(false);
    }//GEN-LAST:event_sortTitleDefMouseClicked

    private void sortYearDefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortYearDefMouseClicked
        // TODO add your handling code here:
        panelSortDef.setVisible(false);
        panelSortTitle.setVisible(false);
        panelSortYear.setVisible(true);
        panelSortRating.setVisible(false);
    }//GEN-LAST:event_sortYearDefMouseClicked

    private void sortRatingDefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortRatingDefMouseClicked
        // TODO add your handling code here:
        panelSortDef.setVisible(false);
        panelSortTitle.setVisible(false);
        panelSortYear.setVisible(false);
        panelSortRating.setVisible(true);
    }//GEN-LAST:event_sortRatingDefMouseClicked

    private void sortYearTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortYearTitleMouseClicked
        // TODO add your handling code here:
        panelSortDef.setVisible(false);
        panelSortTitle.setVisible(false);
        panelSortYear.setVisible(true);
        panelSortRating.setVisible(false);
    }//GEN-LAST:event_sortYearTitleMouseClicked

    private void sortRatingTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortRatingTitleMouseClicked
        // TODO add your handling code here:
        panelSortDef.setVisible(false);
        panelSortTitle.setVisible(false);
        panelSortYear.setVisible(false);
        panelSortRating.setVisible(true);
    }//GEN-LAST:event_sortRatingTitleMouseClicked

    private void sortTitleYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortTitleYearMouseClicked
        // TODO add your handling code here:
        panelSortDef.setVisible(false);
        panelSortTitle.setVisible(true);
        panelSortYear.setVisible(false);
        panelSortRating.setVisible(false);
    }//GEN-LAST:event_sortTitleYearMouseClicked

    private void sortRatingYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortRatingYearMouseClicked
        // TODO add your handling code here:
        panelSortDef.setVisible(false);
        panelSortTitle.setVisible(false);
        panelSortYear.setVisible(false);
        panelSortRating.setVisible(true);
    }//GEN-LAST:event_sortRatingYearMouseClicked

    private void sortTitleRatingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortTitleRatingMouseClicked
        // TODO add your handling code here:
        panelSortDef.setVisible(false);
        panelSortTitle.setVisible(true);
        panelSortYear.setVisible(false);
        panelSortRating.setVisible(false);
    }//GEN-LAST:event_sortTitleRatingMouseClicked

    private void sortYearRatingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sortYearRatingMouseClicked
        // TODO add your handling code here:
        panelSortDef.setVisible(false);
        panelSortTitle.setVisible(false);
        panelSortYear.setVisible(true);
        panelSortRating.setVisible(false);
    }//GEN-LAST:event_sortYearRatingMouseClicked

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        Connection koneksi;
        KoneksiDatabase daftarFilm = new KoneksiDatabase();
        koneksi = daftarFilm.getConnection();
        try{
            Statement st = koneksi.createStatement();
            String sql = "select * from film";
            ResultSet rs = st.executeQuery(sql);
            String bahasaFilm = "";
            while(rs.next()){
                Integer noFilm = Integer.valueOf(rs.getString("ID"));
                String namaFilm = String.valueOf(rs.getString("title"));
                Integer tahunRilis = Integer.valueOf(rs.getString("Release_year"));
                Integer ratingFilm = Integer.valueOf(rs.getString("rating"));
                String deskripsiFilm = String.valueOf(rs.getString("description"));
                switch(String.valueOf(rs.getString("languageID"))){
                case "1":
                    bahasaFilm = "Indonesia";
                    break;
                case "2":
                    bahasaFilm = "English";
                    break;
                case "3":
                    bahasaFilm = "Japan";
                    break;
                case "4":
                    bahasaFilm = "China";
                    break;
                case "5":
                    bahasaFilm = "Thailand";
                    break;
                case "6":
                    bahasaFilm = "India";
                    break;
                case "7":
                    bahasaFilm = "German";
                    break;    
            }
                
                String iniTable[] = {noFilm.toString(), namaFilm, tahunRilis.toString(), deskripsiFilm, ratingFilm.toString(), bahasaFilm};
                DefaultTableModel modelTablenya = (DefaultTableModel)jTable1.getModel();
                modelTablenya.addRow(iniTable);
            }
            System.out.println("Tabel Film berhasil muncul!");
        }catch(SQLException ex){
            Logger.getLogger (Movies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1FocusGained

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Connection koneksi;
        KoneksiDatabase daftarFilm = new KoneksiDatabase();
        koneksi = daftarFilm.getConnection(); 
        String querys = "DELETE FROM `film` WHERE ID = ?";
        try{
            PreparedStatement pstmt = koneksi.prepareStatement(querys);
            int BarisTerpilih = jTable1.getSelectedRow();
            pstmt.setInt(1, Integer.parseInt(jTable1.getModel().getValueAt(BarisTerpilih, 0).toString()));
            pstmt.executeUpdate();
            System.out.println("Film berhasil ditambahkan!");
        }catch(SQLException ex){
            Logger.getLogger (Movies.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel modelTablenya = (DefaultTableModel)jTable1.getModel();
        int terpilih = jTable1.getSelectedRow();
                modelTablenya.removeRow(terpilih);
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMovies;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel countCustomer;
    private javax.swing.JLabel countMovies;
    private javax.swing.JLabel countStaff;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPageCategories;
    private javax.swing.JPanel mainPageDashboard;
    private javax.swing.JPanel mainPageMovies;
    private javax.swing.JLabel menuCategories;
    private javax.swing.JLabel menuCategories1;
    private javax.swing.JLabel menuDashboard;
    private javax.swing.JLabel menuDashboard1;
    private javax.swing.JLabel menuDashboard2;
    private javax.swing.JLabel menuDashboard3;
    private javax.swing.JLabel menuMovies;
    private javax.swing.JLabel menuMovies2;
    private javax.swing.JLabel menuMoviesHead;
    private javax.swing.JLabel pageCategories;
    private javax.swing.JLabel pageDashboard;
    private javax.swing.JLabel pageMovies;
    private javax.swing.JPanel panelCategories;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelMovies;
    private javax.swing.JPanel panelMoviesHead;
    private javax.swing.JPanel panelSortDef;
    private javax.swing.JPanel panelSortRating;
    private javax.swing.JPanel panelSortTitle;
    private javax.swing.JPanel panelSortYear;
    private javax.swing.JLabel sidebarCategories;
    private javax.swing.JLabel sidebarDashboard;
    private javax.swing.JLabel sidebarMovies;
    private javax.swing.JLabel sidebarMoviesHead;
    private javax.swing.JLabel sortDef;
    private javax.swing.JLabel sortRating;
    private javax.swing.JLabel sortRatingDef;
    private javax.swing.JLabel sortRatingRating;
    private javax.swing.JLabel sortRatingTitle;
    private javax.swing.JLabel sortRatingYear;
    private javax.swing.JLabel sortTitle;
    private javax.swing.JLabel sortTitleDef;
    private javax.swing.JLabel sortTitleRating;
    private javax.swing.JLabel sortTitleTitle;
    private javax.swing.JLabel sortTitleYear;
    private javax.swing.JLabel sortYear;
    private javax.swing.JLabel sortYearDef;
    private javax.swing.JLabel sortYearRating;
    private javax.swing.JLabel sortYearTitle;
    private javax.swing.JLabel sortYearYear;
    private javax.swing.JLabel sortingLabel;
    // End of variables declaration//GEN-END:variables
}
